module.exports=[
    {
     "sub_id": 70820,
     "sub_code": "EE301",
     "sub_name": "POWER ELECTRONICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 1,
     "course_type": "compulsory",
     "asses_plan": "15-25-20-40",
     "lectures": 3,
     "tutorials": 0,
     "practicals": 2,
     "course_coordinator_name": "Prof. Madhusudan Singh"
    },
    {
     "sub_id": 70821,
     "sub_code": "EE303",
     "sub_name": "POWER TRANSMISSION AND DISTRIBUTION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 2,
     "course_type": "compulsory",
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Prof. Pragati Kumar"
    },
    {
     "sub_id": 70822,
     "sub_code": "AE307",
     "sub_name": "COMBUSTION GENERATED POLLUTION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "15-25-20-40",
     "lectures": 3,
     "tutorials": 0,
     "practicals": 2,
     "course_coordinator_name": "Dr. Venkat Vanjari"
    },
    {
     "sub_id": 70823,
     "sub_code": "AE309",
     "sub_name": "OPERATIONS RESEARCH",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70824,
     "sub_code": "AE311",
     "sub_name": "TYRE TECHNOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "course_type": "compulsory"
    },
    {
     "sub_id": 70825,
     "sub_code": "AE317",
     "sub_name": "POWER UNITS AND TRANSMISSION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "course_type": "compulsory"
    },
    {
     "sub_id": 70826,
     "sub_code": "BT325",
     "sub_name": "CELL BIOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "course_type": "compulsory"
    },
    {
     "sub_id": 70827,
     "sub_code": "CE307",
     "sub_name": "ADVANCED GEO-TECHNICAL ENGINEERING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70828,
     "sub_code": "CE317",
     "sub_name": "SOLID WASTE MANAGEMENT AND AIR POLLUTION CONTROL",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70829,
     "sub_code": "CE319",
     "sub_name": "APPLICATION OF GEO-INFORMATICS REMOTE SENSING AND GIS IN ENGINEERING ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70830,
     "sub_code": "CO305",
     "sub_name": "INFORMATION THEORY AND CODING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70831,
     "sub_code": "CO313",
     "sub_name": "COMPUTER GRAPHICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70832,
     "sub_code": "EC311",
     "sub_name": "ALGORITHM ANALYSIS AND DESIGN",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70833,
     "sub_code": "EC313",
     "sub_name": "MICROPROCESSORS AND INTERFACING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70834,
     "sub_code": "EC323",
     "sub_name": "CONTROL SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70835,
     "sub_code": "EE305",
     "sub_name": "SIGNALS AND SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70836,
     "sub_code": "EE309",
     "sub_name": "SPECIAL ELECTRICAL MACHINES",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70837,
     "sub_code": "EE315",
     "sub_name": "DIGITAL CONTROL AND STATE VARIABLE ANALYSIS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70838,
     "sub_code": "EE317",
     "sub_name": "RENEWABLE ENERGY SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70839,
     "sub_code": "EL317",
     "sub_name": "RENEWABLE ENERGY SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70840,
     "sub_code": "EL315",
     "sub_name": "DIGITAL CONTROL AND STATE VARIABLE ANALYSIS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70841,
     "sub_code": "EN305",
     "sub_name": "SOIL POLLUTION AND REMEDIATION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70842,
     "sub_code": "EN311",
     "sub_name": "CLIMATE CHANGE AND CDM",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70843,
     "sub_code": "EP305",
     "sub_name": "ATOMIC AND MOLECULAR PHYSICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70844,
     "sub_code": "EP307",
     "sub_name": "BIOPHYSICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E1",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70845,
     "sub_code": "EP309",
     "sub_name": "QUANTUM INFORMATION AND COMPUTING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70846,
     "sub_code": "EP311",
     "sub_name": "COMPUTER NETWORKING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70847,
     "sub_code": "IT307",
     "sub_name": "PATTERN RECOGNITION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70848,
     "sub_code": "IT321",
     "sub_name": "MALWARE ANALYSIS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70849,
     "sub_code": "MC305",
     "sub_name": "OPERATION RESEARCH",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70850,
     "sub_code": "MC315",
     "sub_name": "MODERN ALGEBRA",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70851,
     "sub_code": "PE307",
     "sub_name": "FINITE ELEMENT METHOD",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70852,
     "sub_code": "PE315",
     "sub_name": "MECHATRONICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70853,
     "sub_code": "PT315",
     "sub_name": "PACKAGING TECHNOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70854,
     "sub_code": "PT321",
     "sub_name": "BIOSENSOR TECHNOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70855,
     "sub_code": "SE307",
     "sub_name": "COMPUTER GRAPHICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70856,
     "sub_code": "SE321",
     "sub_name": "ARTIFICIAL INTELLIGENCE",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 3,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70857,
     "sub_code": "AE307",
     "sub_name": "COMBUSTION GENERATED POLLUTION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70858,
     "sub_code": "AE309",
     "sub_name": "OPERATIONS RESEARCH",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70859,
     "sub_code": "AE311",
     "sub_name": "TYRE TECHNOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70860,
     "sub_code": "AE317",
     "sub_name": "POWER UNITS AND TRANSMISSION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70861,
     "sub_code": "BT325",
     "sub_name": "CELL BIOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70862,
     "sub_code": "CE307",
     "sub_name": "ADVANCED GEO-TECHNICAL ENGINEERING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70863,
     "sub_code": "CE317",
     "sub_name": "SOLID WASTE MANAGEMENT AND AIR POLLUTION CONTROL",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70864,
     "sub_code": "CE319",
     "sub_name": "APPLICATION OF GEO-INFORMATICS REMOTE SENSING AND GIS IN ENGINEERING ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70865,
     "sub_code": "CO305",
     "sub_name": "INFORMATION THEORY AND CODING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E2",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70866,
     "sub_code": "CO313",
     "sub_name": "COMPUTER GRAPHICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70867,
     "sub_code": "EC311",
     "sub_name": "ALGORITHM ANALYSIS AND DESIGN",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70868,
     "sub_code": "EC313",
     "sub_name": "MICROPROCESSORS AND INTERFACING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70869,
     "sub_code": "EC323",
     "sub_name": "CONTROL SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70870,
     "sub_code": "EE305",
     "sub_name": "SIGNALS AND SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70871,
     "sub_code": "EE309",
     "sub_name": "SPECIAL ELECTRICAL MACHINES",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70872,
     "sub_code": "EE315",
     "sub_name": "DIGITAL CONTROL AND STATE VARIABLE ANALYSIS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70873,
     "sub_code": "EE317",
     "sub_name": "RENEWABLE ENERGY SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70874,
     "sub_code": "EL317",
     "sub_name": "RENEWABLE ENERGY SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70875,
     "sub_code": "EL315",
     "sub_name": "DIGITAL CONTROL AND STATE VARIABLE ANALYSIS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70876,
     "sub_code": "EN305",
     "sub_name": "SOIL POLLUTION AND REMEDIATION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70877,
     "sub_code": "EN311",
     "sub_name": "CLIMATE CHANGE AND CDM",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70878,
     "sub_code": "EP305",
     "sub_name": "ATOMIC AND MOLECULAR PHYSICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70879,
     "sub_code": "EP307",
     "sub_name": "BIOPHYSICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70880,
     "sub_code": "EP309",
     "sub_name": "QUANTUM INFORMATION AND COMPUTING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70881,
     "sub_code": "EP311",
     "sub_name": "COMPUTER NETWORKING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70882,
     "sub_code": "IT307",
     "sub_name": "PATTERN RECOGNITION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70883,
     "sub_code": "IT321",
     "sub_name": "MALWARE ANALYSIS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70884,
     "sub_code": "MC305",
     "sub_name": "OPERATION RESEARCH",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70885,
     "sub_code": "MC315",
     "sub_name": "MODERN ALGEBRA",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70886,
     "sub_code": "PE307",
     "sub_name": "FINITE ELEMENT METHOD",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70887,
     "sub_code": "PE315",
     "sub_name": "MECHATRONICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70888,
     "sub_code": "PT315",
     "sub_name": "PACKAGING TECHNOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70889,
     "sub_code": "PT321",
     "sub_name": "BIOSENSOR TECHNOLOGY",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70890,
     "sub_code": "SE307",
     "sub_name": "COMPUTER GRAPHICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E3",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70891,
     "sub_code": "SE321",
     "sub_name": "ARTIFICIAL INTELLIGENCE",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 4,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 4,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70892,
     "sub_code": "CO357",
     "sub_name": "OPERATING SYSTEM",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70893,
     "sub_code": "CO361",
     "sub_name": "DATABASE MANAGEMENT SYSTEM",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70894,
     "sub_code": "EC353",
     "sub_name": "COMPUTER VISION",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70895,
     "sub_code": "EE355",
     "sub_name": "INSTRUMENTATION SYSTEMS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70896,
     "sub_code": "EN353",
     "sub_name": "OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70897,
     "sub_code": "EP351",
     "sub_name": "PHYSICS OF ENGINEERING MATERIALS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70898,
     "sub_code": "HM351",
     "sub_name": "ECONOMETRICS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70899,
     "sub_code": "IT353",
     "sub_name": "DATA STRUCTURES AND ALGORITHMS ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70900,
     "sub_code": "IT357",
     "sub_name": "INTERNET AND WEB PROGRAMMING ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70901,
     "sub_code": "IT359",
     "sub_name": "JAVA PROGRAMMING",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70902,
     "sub_code": "ME351",
     "sub_name": "POWER PLANT ENGINEERING ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70903,
     "sub_code": "ME359",
     "sub_name": "REFRIGERATION AND AIR CONDITIONING ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70700,
     "sub_code": "PE353",
     "sub_name": "SUPPLY CHAIN MANAGEMENT",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70701,
     "sub_code": "PE361",
     "sub_name": "TOTAL QUALITY MANAGEMENT",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70702,
     "sub_code": "PT361",
     "sub_name": "HIGH PERFORMANCE POLYMERS",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 3,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 5,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 70703,
     "sub_code": "HU303",
     "sub_name": "PROFESSIONAL ETHICS AND HUMAN VALUES ",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 2,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 6,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    },
    {
     "sub_id": 77971,
     "sub_code": "MOOC",
     "sub_name": "MOOC COURSE",
     "minor": "NULL",
     "sub_imax_m": 0,
     "sub_emax_m": 10,
     "min_pass_m": 4,
     "sub_credit": 2,
     "th_pr": "TH",
     "num": 5,
     "sp_code": "EE",
     "aprog": "BTECH",
     "scheme_year": 2015,
     "sub_no": 6,
     "slot": "E4",
     "slot_count": 1,
     "course_type": "elective",
     "course_group": "GEC",
     "group_count": 2,
     "asses_plan": "25-0-25-50",
     "lectures": 3,
     "tutorials": 1,
     "practicals": 0,
     "course_coordinator_name": "Mr. Saurabh Mishra"
    }
   ]